# Generated by Django 5.1.6 on 2025-02-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=20, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField()),
                ('desc', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField()),
                ('thumb', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('vid', models.CharField(max_length=50, unique=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
